### ISSUE TITLE
More of a request for documentation

### ISSUE THREAD

**Issue by user71k** [jordanclark/cfamazonproductad#2]
Hi , Thanks for creating cfamazonproductad, 
I wish I could just use it with ColdFusion instead of loading Coldbox. but my issue is that there is no documentation to follow about changing your country  its giving me an error because it wants to use the default.
Id pay you If I could , any help is super appreciated!
I tried changing this string defaultMarketplace= "www.amazon.ca" with no luck so far...

<cfscript>
amz = new amazonProductAd5(
	accessKeyId= "AAAAAAAAAAAAAAAAAA"
,	secretAccessKey= "afafafafafaf7asdfafafafaZasfafaf"
,	partnerTag= "xyz-200"
                                                                                                  ,	defaultMarketplace= "www.amazon.ca"
).usDefaults();
test= amz.SearchItems( "fred", "ItemInfo.Title" );
dump( test );
</cfscript>

**Comment by jordanclark** [comment]
Hi there,

This module doesn't use coldbox at all, it's just standard coldfusion.

If you look at the main cfc you'll see it's got support for all the Amazon
markets with convenience methods. The example sets this up with
.usDefaults() you could replace this with .canadaDefaults() method to set
the correct market and endpoint.

I hope that helps,
Jordan

**Comment by user71k** [comment]
Yep already ahead of you,  thanks for the reply, keep up the great work!
